baseURL = "https://nimajason.com"
defaultContentLanguage = "ti"
defaultContentLanguageInSubdir = true
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]
summaryLength = 20
paginate = 5
disqusShortname = "https-www-nimajason-com"

[params]
	cloudinary_url = "https://res.cloudinary.com/ml7757/image/upload/nimajason"
	DateForm = "2.01.2006 15:04 MST"

[languages]
  [languages.ti]
    contentDir = "content/tigrinya"
    languageName = "Tigrinya"
    weight = 1
		title = "ኣብ ትግርኛ ዝተጻሕፈ ግጥሚታት"
		[languages.ti.params]
			siteDescription = "ግጥሚታትን ዓንቀጻትን ኤርትራ ብቛንቋ ትግርኛ"
	[languages.en]
    contentDir = "content/english"
    languageName = "English"
    weight = 2
		title = "Poems in Tigrinya"
		[languages.en.params]
			siteDescription = "Poems and Eritrean articles in the Tigrinya language"
