baseURL = "https://nimajason.com"
defaultContentLanguage = "ti"
defaultContentLanguageInSubdir = true
summaryLength = 20
paginate = 5

[params]
	cloudinary_url = "https://res.cloudinary.com/ml7757/image/upload/nimajason"
	DateForm = "2.01.2006 15:04 MST"

[languages]
  [languages.ti]
    contentDir = "content/tigrinya"
    languageName = "Tigrinya"
    weight = 1
		title = "ኣብ ጢግሪንያ እተጻሕፈ ግጥምታት"
		[languages.ti.params]
			siteDescription = "ግጥምታትን ዓንቀጻት ኤርትረኛን ብቛንቋ ጢግሪንያ"
	[languages.en]
    contentDir = "content/english"
    languageName = "English"
    weight = 2
		title = "Poems in Tigrinya"
		[languages.en.params]
			siteDescription = "Poems and Eritrean articles in the Tigrinya language"
